In [7]:
!pip install -U fg-data-profiling

Collecting fg-data-profiling
  Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.5.2)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.6.17)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->fg-data-profiling) (1.17.0)
Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 kB 9.2 MB/s eta 0:00:00
Installing collected packages: fg-data-profiling
Successfully installed fg-data-profiling-4.19.1

In [21]:
import pandas as pd
import numpy as np
import data_profiling
from data_profiling import ProfileReport

In [22]:
uploaded=files.upload()

Saving dirty_cafe_sales.csv to dirty_cafe_sales.csv

In [23]:
df=pd.read_csv("dirty_cafe_sales.csv")

In [24]:
Profile=ProfileReport(df, title='house', explorative=True)
Profile.to_file('reporthouse.html')
files.download('reporthouse.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|█▎        | 1/8 [00:00<00:01,  6.13it/s]
 38%|███▊      | 3/8 [00:00<00:00, 11.56it/s]
 62%|██████▎   | 5/8 [00:00<00:00, 12.65it/s]
100%|██████████| 8/8 [00:00<00:00, 12.85it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [25]:
df.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [28]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [27]:
df.shape

(10000, 8)

In [29]:
df.columns=( df.columns.str.replace(' ','_').str.lower())

In [30]:
df.head(10)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [31]:
missing=df.isnull().mean()*100
print(missing)

transaction_id       0.00
item                 3.33
quantity             1.38
price_per_unit       1.79
total_spent          1.73
payment_method      25.79
location            32.65
transaction_date     1.59
dtype: float64

In [32]:
n_dups=df.duplicated().sum()
print(n_dups)

0

In [33]:
df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head(10)

Empty DataFrame
Columns: [transaction_id, item, quantity, price_per_unit, total_spent, payment_method, location, transaction_date]
Index: []

In [34]:
df.isnull().sum()

transaction_id         0
item                 333
quantity             138
price_per_unit       179
total_spent          173
payment_method      2579
location            3265
transaction_date     159
dtype: int64

In [35]:
df.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [37]:
df["quantity"].unique()

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan], dtype=object)

In [40]:
quantity_numeric = pd.to_numeric(df["quantity"], errors="coerce")
df[quantity_numeric.isna()]

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
20,TXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04
55,TXN_5522862,Cookie,ERROR,1.0,2.0,Credit Card,Takeaway,2023-03-19
57,TXN_2080895,Cake,UNKNOWN,3.0,3.0,Digital Wallet,In-store,2023-04-19
66,TXN_8501819,Juice,NaN,3.0,6.0,Cash,NaN,2023-03-30
117,TXN_2148617,Juice,ERROR,3.0,9.0,Digital Wallet,UNKNOWN,2023-01-10
...,...,...,...,...,...,...,...,...
9932,TXN_8502079,Tea,UNKNOWN,1.5,3.0,Cash,NaN,2023-04-20
9935,TXN_9778251,Tea,ERROR,1.5,6.0,NaN,Takeaway,2023-11-09
9944,TXN_7495283,Cake,UNKNOWN,3.0,15.0,Credit Card,Takeaway,2023-04-14
9957,TXN_6487003,Coffee,ERROR,2.0,8.0,Credit Card,Takeaway,2023-11-15
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27

In [41]:
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")

median = df["quantity"].median()

df["quantity"] = df["quantity"].fillna(median)

In [42]:
df["quantity"].isna().sum()

np.int64(0)

In [47]:
df.head(21)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3.0,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2.0,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,3.0,4.0,20.0,Cash,In-store,2023-04-04

In [49]:
df.columns

Index(['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent',
       'payment_method', 'location', 'transaction_date'],
      dtype='object')

In [45]:
df["quantity"]=pd.to_numeric(df["quantity"], errors="coerce")

In [50]:
df["item"].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [56]:
df["item"].value_counts(dropna=False)

item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

In [54]:
item_string = pd.to_numeric(df["item"], errors="coerce")
df[item_string.isna()]

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [72]:
df.head(10)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,UNKNOWN,2023-10-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,ERROR

In [57]:
df["item"] = df["item"].replace(["ERROR", "UNKNOWN"], np.nan)

In [58]:
df = df.dropna(subset=["item"])

In [59]:
df.shape

(9031, 8)

In [73]:
df["price_per_unit"].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', 3.0, 4.0, 5.0, 1.5, nan,
       1.0, 2.0], dtype=object)

In [61]:
df = df.copy()

In [62]:
df["price_per_unit"] = df["price_per_unit"].replace(["ERROR", "UNKNOWN"], np.nan)

In [66]:
df["price_per_unit"].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan], dtype=object)

In [70]:
df[df["item"] == "Juice"]

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10
43,TXN_9620080,Juice,4.0,3.0,12.0,NaN,Takeaway,2023-10-02
46,TXN_8078640,Juice,4.0,3.0,12.0,Digital Wallet,In-store,2023-11-03
...,...,...,...,...,...,...,...,...
9960,TXN_3546629,Juice,5.0,3.0,15.0,NaN,In-store,2023-03-04
9967,TXN_8563793,Juice,4.0,3.0,12.0,NaN,In-store,2023-03-26
9977,TXN_5548914,Juice,2.0,3.0,ERROR,Digital Wallet,In-store,2023-11-04
9987,TXN_1784478,Juice,5.0,3.0,15.0,Cash,NaN,2023-07-31
9989,TXN_1741685,Juice,5.0,3.0,15.0,Cash,NaN,2023-08-18

In [71]:
price_map = {
    "Coffee": 2,
    "Cake": 3,
    "Cookie": 1,
    "Salad": 5,
    "Smoothie": 4,
    "Sandwich": 4,
    "Tea": 1.5
}

mask = df["price_per_unit"].isna()

df.loc[mask, "price_per_unit"] = df.loc[mask, "item"].map(price_map)

In [74]:
df["total_spent"] = df["total_spent"].replace(["ERROR", "UNKNOWN"], np.nan)

In [75]:
df["total_spent"].unique()

array(['4.0', '12.0', nan, '10.0', '20.0', '16.0', '25.0', '8.0', '5.0',
       '15.0', '6.0', '2.0', '9.0', '3.0', '1.0', '7.5', '4.5', '1.5'],
      dtype=object)

In [78]:
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["price_per_unit"] = pd.to_numeric(df["price_per_unit"], errors="coerce")
df["total_spent"] = pd.to_numeric(df["total_spent"], errors="coerce")

In [79]:
mask = df["total_spent"].isna()

df.loc[mask, "total_spent"] = (df.loc[mask, "quantity"] * df.loc[mask, "price_per_unit"])

In [80]:
df.head(15)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,UNKNOWN,2023-10-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24

In [82]:
df.dtypes

transaction_id       object
item                 object
quantity            float64
price_per_unit      float64
total_spent         float64
payment_method       object
location             object
transaction_date     object
dtype: object

In [84]:
df["payment_method"].value_counts(dropna=False)

payment_method
NaN               2330
Digital Wallet    2065
Cash              2046
Credit Card       2043
ERROR              286
UNKNOWN            261
Name: count, dtype: int64

In [85]:
df["payment_method"] = df["payment_method"].replace(["ERROR", "UNKNOWN"], np.nan)

In [86]:
df["payment_method"] = df["payment_method"].fillna(df["payment_method"].mode()[0])

In [88]:
df["payment_method"].value_counts(dropna=False)

payment_method
Digital Wallet    4942
Cash              2046
Credit Card       2043
Name: count, dtype: int64

In [87]:
df["location"].value_counts(dropna=False)

location
NaN         2945
Takeaway    2725
In-store    2723
ERROR        326
UNKNOWN      312
Name: count, dtype: int64

In [89]:
df["location"] = df["location"].replace(["ERROR", "UNKNOWN"], np.nan)

In [90]:
df["location"] = df["location"].fillna(df["location"].mode()[0])

In [91]:
df["location"].value_counts(dropna=False)

location
Takeaway    6308
In-store    2723
Name: count, dtype: int64

In [92]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"], errors="coerce")

In [93]:
df["transaction_date"].isna().sum()

np.int64(418)

In [94]:
df = df.dropna(subset=["transaction_date"])

In [95]:
df["transaction_date"].isna().sum()

np.int64(0)

In [97]:
df.describe()

          quantity  price_per_unit  total_spent               transaction_date
count  8613.000000     8554.000000  8612.000000                           8613
mean      3.025659        2.951777     8.941419  2023-07-02 03:54:44.012539392
min       1.000000        1.000000     1.000000            2023-01-01 00:00:00
25%       2.000000        2.000000     4.000000            2023-04-01 00:00:00
50%       3.000000        3.000000     8.000000            2023-07-02 00:00:00
75%       4.000000        4.000000    12.000000            2023-10-03 00:00:00
max       5.000000        5.000000    25.000000            2023-12-31 00:00:00
std       1.388081        1.282720     6.013125                            NaN

In [99]:
df.shape

(8613, 8)

In [100]:
df.dtypes

transaction_id              object
item                        object
quantity                   float64
price_per_unit             float64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
dtype: object

In [104]:
df.isnull().sum()

transaction_id       0
item                 0
quantity             0
price_per_unit      59
total_spent          1
payment_method       0
location             0
transaction_date     0
dtype: int64

In [111]:
df[df["price_per_unit"].isna()]

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
161,TXN_7965998,Juice,1.0,NaN,3.0,Credit Card,In-store,2023-11-02
485,TXN_8818168,Juice,4.0,NaN,12.0,Digital Wallet,Takeaway,2023-07-20
562,TXN_3789752,Juice,3.0,NaN,9.0,Digital Wallet,Takeaway,2023-12-16
643,TXN_4266787,Juice,4.0,NaN,12.0,Credit Card,Takeaway,2023-01-12
779,TXN_4015710,Juice,4.0,NaN,12.0,Cash,Takeaway,2023-05-18
801,TXN_2393500,Juice,1.0,NaN,3.0,Credit Card,In-store,2023-12-15
834,TXN_6376175,Juice,4.0,NaN,12.0,Digital Wallet,Takeaway,2023-02-24
1017,TXN_1991104,Juice,2.0,NaN,6.0,Digital Wallet,Takeaway,2023-11-29
1124,TXN_8135614,Juice,2.0,NaN,6.0,Digital Wallet,Takeaway,2023-01-28
1256,TXN_5858988,Juice,1.0,NaN,3.0,Credit Card,Takeaway,2023-06-24
1868,TXN_5108804,Juice,1.0,NaN,3.0,Digital Wallet,In-store,2023-09-26
1958,TXN_8707598,Juice,4.0,NaN,12.0,Credit Card,Takeaway,2023-10-22
2028,TXN_2193092,Juice,4.0,NaN,12.0,Digital Wallet,Takeaway,2023-10-30
2123,TXN_5396727,Juice,2.0,NaN,6.0,Credit Card,Takeaway,2023-10-13
2262,TXN_3854036,Juice,3.0,NaN,9.0,Cash,Takeaway,2023-11-07
2319,TXN_5737831,Juice,4.0,NaN,12.0,Digital Wallet,Takeaway,2023-05-15
2554,TXN_2217295,Juice,4.0,NaN,12.0,Credit Card,In-store,2023-11-22
2607,TXN_1214868,Juice,4.0,NaN,12.0,Cash,In-store,2023-07-30
2719,TXN_6954434,Juice,3.0,NaN,9.0,Cash,Takeaway,2023-02-23
2747,TXN_4617139,Juice,4.0,NaN,12.0,Digital Wallet,Takeaway,2023-04-12
2862,TXN_8279865,Juice,1.0,NaN,3.0,Cash,Takeaway,2023-07-18
2974,TXN_8571836,Juice,3.0,NaN,9.0,Cash,Takeaway,2023-12-27
3223,TXN_6504165,Juice,3.0,NaN,9.0,Cash,Takeaway,2023-02-13
3464,TXN_7630912,Juice,2.0,NaN,6.0,Credit Card,Takeaway,2023-01-04
4025,TXN_5671997,Juice,3.0,NaN,9.0,Digital Wallet,Takeaway,2023-09-03
4107,TXN_2972777,Juice,4.0,NaN,12.0,Credit Card,Takeaway,2023-04-08
4170,TXN_9317529,Juice,4.0,NaN,12.0,Credit Card,Takeaway,2023-07-10
4631,TXN_9024186,Juice,2.0,NaN,6.0,Cash,Takeaway,2023-12-17
4888,TXN_1509627,Juice,4.0,NaN,12.0,Digital Wallet,Takeaway,2023-03-23
4889,TXN_7813066,Juice,1.0,NaN,3.0,Digital Wallet,Takeaway,2023-02-28
4892,TXN_2991726,Juice,5.0,NaN,15.0,Digital Wallet,In-store,2023-09-01
5001,TXN_9691873,Juice,2.0,NaN,6.0,Digital Wallet,Takeaway,2023-02-15
5219,TXN_1559512,Juice,5.0,NaN,15.0,Credit Card,Takeaway,2023-11-28
5291,TXN_6846020,Juice,5.0,NaN,15.0,Digital Wallet,Takeaway,2023-05-03
5656,TXN_8855046,Juice,3.0,NaN,9.0,Digital Wallet,Takeaway,2023-12-05
5886,TXN_2252244,Juice,2.0,NaN,6.0,Credit Card,Takeaway,2023-03-10
5927,TXN_6144244,Juice,3.0,NaN,9.0,Cash,Takeaway,2023-01-08
5986,TXN_1598214,Juice,1.0,NaN,3.0,Credit Card,Takeaway,2023-01-07
6131,TXN_2136226,Juice,2.0,NaN,6.0,Digital Wallet,In-store,2023-12-12
6575,TXN_7868470,Juice,3.0,NaN,9.0,Digital Wallet,Takeaway,2023-04-14
6922,TXN_4423879,Juice,5.0,NaN,15.0,Digital Wallet,Takeaway,2023-02-12
7010,TXN_6347567,Juice,5.0,NaN,15.0,Cash,In-store,2023-03-31
7022,TXN_1236779,Juice,3.0,NaN,9.0,Credit Card,In-store,2023-12-29
7467,TXN_4989644,Juice,5.0,NaN,15.0,Digital Wallet,Takeaway,2023-11-13
7718,TXN_7177709,Juice,5.0,NaN,15.0,Digital Wallet,Takeaway,2023-03-08
7987,TXN_7400015,Juice,4.0,NaN,12.0,Cash,Takeaway,2023-01-27
8058,TXN_9354349,Juice,1.0,NaN,3.0,Credit Card,Takeaway,2023-02-12
8436,TXN_3641356,Juice,3.0,NaN,9.0,Credit Card,In-store,2023-07-26
8481,TXN_3829375,Juice,5.0,NaN,15.0,Cash,Takeaway,2023-12-18
8676,TXN_3771902,Juice,5.0,NaN,15.0,Cash,Takeaway,2023-03-31
8681,TXN_2894525,Juice,3.0,NaN,9.0,Digital Wallet,Takeaway,2023-04-16
8715,TXN_9265423,Juice,1.0,NaN,3.0,Digital Wallet,Takeaway,2023-10-20
9373,TXN_9018366,Juice,5.0,NaN,15.0,Cash,Takeaway,2023-03-31
9389,TXN_4239859,Juice,1.0,NaN,3.0,Digital Wallet,Takeaway,2023-02-03
9437,TXN_6883187,Juice,2.0,NaN,6.0,Digital Wallet,Takeaway,2023-11-16
9500,TXN_2009407,Juice,5.0,NaN,15.0,Cash,Takeaway,2023-05-05
9753,TXN_3507013,Juice,1.0,NaN,3.0,Digital Wallet,In-store,2023-01-16
9893,TXN_3809533,Juice,2.0,NaN,NaN,Digital Wallet,Takeaway,2023-02-02
9924,TXN_5981429,Juice,2.0,NaN,6.0,Digital Wallet,Takeaway,2023-12-24

In [112]:
df.loc[
    (df["item"] == "Juice") & (df["price_per_unit"].isna()),
    "price_per_unit"
] = 3

In [113]:
df.loc[
    (df["item"] == "Juice") & (df["price_per_unit"].isna()),
    "price_per_unit"
] = 3

In [116]:
df.loc[df["total_spent"].isna(), "total_spent"] = (
    df["quantity"] * df["price_per_unit"]
)

In [119]:
Profile=ProfileReport(df, title='cafe', explorative=True)
Profile.to_file('reportcafe.html')
files.download('reportcafe.html')

/usr/local/lib/python3.12/dist-packages/data_profiling/utils/dataframe.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"index": "df_index"}, inplace=True)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|█▎        | 1/8 [00:00<00:01,  4.82it/s]
100%|██████████| 8/8 [00:00<00:00, 20.80it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]